### PR TITLE
Continued use case style guide editing

### PR DESCRIPTION
**Pull request by marisalim**
- adding in issue and PR templates
- contribute doc to tab
- other style guide fine-tuning

preview here: https://cfde-usecases.readthedocs-hosted.com/en/styleguidecont/

### CODE REVIEW

**Comment by marisalim** [comment]
@ACharbonneau do you want to leave the Overview section (same as glossary pg) on the Home page? There is a new 'About' tab that has how to contribute and glossary now.

https://cfde-usecases.readthedocs-hosted.com/en/styleguidecont/

**Comment by ACharbonneau** [comment]
At this part:

> If you are submitting a pull request, please create one pull request per use case so admin can check the complete change.

>First, preview new changes:

>Create a new branch in the use cases repo
>Use the use case file templates to add your new use case files

You're assuming that they do branches like we do, and that they *can* do branches like we do. Many people will clone the repo and do their changes in there...like normal people do github. We should have instructions for both. I think that someone who clones it and makes a change should still be able to push to preview and look at their changes, but I'm not actually sure. Can you make a dummy github account and clone it and check? Because if they *need* to do it our way, we need to explain it more.

**Comment by marisalim** [comment]
to add: 
- for PRs, only contributers can merge to any of the repo's branches, so they'd have to request a maintainer to merge to both preview and master branches. they can make the PR a draft, but they can't assign reviewers in the side tab. they can `@` reference a maintainer tho and ask them to review and merge. 
- non-contributers can NOT make a new branch directly in the usecases repo, so they must 1) write an issue for help OR 2) fork the repo/make new branch/make changes/PR/request maintainer. they can git clone the forked repo to local, but they can't directly push things to the nih-cfde/usecases repo.
- took ~15 minutes to render preview, 30 mins to revert changes

**Comment by marisalim** [comment]
@ACharbonneau I rewrote the issue and PR instructions a bit to reflect this [comment](https://github.com/nih-cfde/usecases/pull/30#issuecomment-665978132). But I'm not sure what the PR steps should be for reviewing/merging. Maybe it should be like what you set up on the published-docs website ...

Right now non-contributors can't merge to preview. Should we be moderating the preview merge process? Do we want users to check the preview website vs. us? And then, if it looks ok on the preview, can we have a bot auto-generate a PR to the master branch? at which point they should request review from us...etc.

**Comment by ACharbonneau** [comment]
I can set up a bot to auto-check and merge PRs to preview. I'd like the submitter to be able to see their preview without us having to do anything

**Comment by ACharbonneau** [comment]
For the PR template:

- [x] add the yaml. It would be good if they started with a title that says something like "change to informative title" rather than it just being an easy to ignore note
- [x] It should have mini-instructions for how to preview embedded in it
- [x] It's nice to make them checklists. The submitter checks off that they did those things, whatever they are. Then I can have a bot do things based on what is checked

Other templates:

- [x] We should have at least two issue options. The one you have, and one for changes/suggestions/whatever. 

Issue links are placeholders right now until the changes are pushed to master

**Comment by marisalim** [comment]
@ACharbonneau  there are 2 broken links on the style guide doc - I can't find the CODEOFCONDUCT.md or LICENSE.md files. Did they move?

UPDATE: amanda is making a repo to automagic the CoCs :)

**Comment by marisalim** [comment]
have 3 issue templates, also a note about labeling issues...perhaps redundant. need to check how submitting to the different issue templates looks

**Comment by ACharbonneau** [comment]
I am in the middle of a thing, so I can't review in detail, but I'm fine with merging so you can check templates and then leaving issues for anything I think needs changed when I can look

**Review by ACharbonneau — APPROVED** [review]
for template checking

**Comment by jeremywalter** [comment]
Somewhere in the past few months this fell out of my head: https://carpentries.github.io/lesson-example/ 
I have seen Carpentries templates used in other places (and Amanda is probably tired of me advocating taking Carpentries things), but... they have a system and style guide and checks... it seems like a good place borrow from, but I don't have enough real Carpentries experience to know how useful it might be.

**Comment by ACharbonneau** [comment]
on the contrary, I'm extremely pro stealing ideas from the carpentries :)

**Comment by marisalim** [comment]
thanks @jeremywalter! i'll incorporate these into usecases and training :)

**Comment by jeremywalter** [comment]
errr... I was trying to put this in training... but hey... multi-purpose! (d'oh)

**Pull request merged**
